#!/usr/bin/env python3
"""
Concatène les sources CSS en un seul main.css avec cache buster auto.

Usage : python3 tools/build-css.py

Sources (dans cet ordre) :
    assets/css/src/00-reset.css
    assets/css/src/01-variables.css
    assets/css/src/02-components.css
    assets/css/src/10-main.css

Sortie :
    assets/css/main.css              (bundle concaténé)
    assets/css/.version              (hash 8 caractères pour cache buster)

Met à jour automatiquement le cache buster dans tous les *.html du repo.
"""

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "assets" / "css" / "src"
OUT_CSS = ROOT / "assets" / "css" / "main.css"
VERSION_FILE = ROOT / "assets" / "css" / ".version"

SOURCES = [
    "00-reset.css",
    "01-variables.css",
    "02-components.css",
    "10-main.css",
]

BANNER_TMPL = "\n/* {sep}\n   {name}\n   {sep} */\n\n"
SEP = "=" * 60


def build_bundle() -> tuple[str, str]:
    """Return (concatenated_css, version_hash)."""
    parts = []
    parts.append("/* AUTO-GENERATED by tools/build-css.py — DO NOT EDIT DIRECTLY */\n")
    parts.append("/* Edit sources in assets/css/src/ then re-run the script. */\n")
    for filename in SOURCES:
        path = SRC_DIR / filename
        if not path.exists():
            raise SystemExit(f"❌ Source manquante : {path}")
        parts.append(BANNER_TMPL.format(sep=SEP, name=filename))
        parts.append(path.read_text(encoding="utf-8").rstrip() + "\n")
    bundle = "".join(parts)
    version = hashlib.sha256(bundle.encode("utf-8")).hexdigest()[:8]
    return bundle, version


def update_html_cache_busters(version: str) -> int:
    """Replace main.css?v=XXX with main.css?v={version} in all HTML files. Returns count."""
    pattern = re.compile(r'(main\.css\?v=)[a-zA-Z0-9]+')
    replacement = rf"\g<1>{version}"
    updated = 0
    for html in ROOT.rglob("*.html"):
        # Skip backup/temp files
        if any(part.startswith(".") for part in html.parts):
            continue
        text = html.read_text(encoding="utf-8")
        new_text, n = pattern.subn(replacement, text)
        if n > 0 and new_text != text:
            html.write_text(new_text, encoding="utf-8")
            updated += n
    return updated


def main():
    bundle, version = build_bundle()
    OUT_CSS.write_text(bundle, encoding="utf-8")
    VERSION_FILE.write_text(version + "\n", encoding="utf-8")
    print(f"✓ {OUT_CSS.relative_to(ROOT)} : {len(bundle):,} bytes")
    print(f"✓ Cache buster : v={version}")

    count = update_html_cache_busters(version)
    print(f"✓ Cache buster mis à jour dans {count} balise(s) <link> de HTML.")


if __name__ == "__main__":
    main()
